### ISSUE TITLE
Want to add pattern questions in c++.

### ISSUE THREAD

**Issue by aritroo** [NirobNabil/Numerical-Analysis#3]
hello @NirobNabil 
Can I add some pattern questions in c++ to this reop???

**Comment by NirobNabil** [comment]
Can you please elaborate? What do you mean by pattern questions?

**Comment by aritroo** [comment]
> Can you please elaborate? What do you mean by pattern questions? 

I am willing to add pattern questions solution like printing pyramid pattern with stars and then diamond pattern .

**Comment by NirobNabil** [comment]
Hello @aritroo really appreciate you willing to contribute to this repo but this repo is mainly focused on numerical analysis methods. If you really want to work with shapes, you can make comparison charts/tables using matplotlib for visualizing the difference between time taken for root finding between different algorithms. If you don't know about numerical methods its okay you dont need to understand the functions. just use time module of python to measure how much time it takes for different functions to run. I've been looking forward to implementing this features. If you can help with this, it will be really appreciated.
